# local environment

server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console # = default value
  jpa:
    hibernate:
      ddl-auto: create-drop # h2는 불필요한 옵션
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
