
# SQL 출력 예쁘게 하는 것.
#  https://velog.io/@devholic/Spring-YAML-%EC%97%AC%EB%9F%AC-%EA%B0%9C-%EC%93%B0%EA%B8%B0
spring:
  config:
    activate:
      on-profile: log
  jpa:
    properties:
      hibernate:
        #       show_sql: true # System.out 방식 로그
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        SQL: debug # logger 방식 로그
        orm:
          jdbc:
            bind: trace